version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: Run tests
          command: docker-compose exec app pipenv run scripts/run_tests
