version: 2.1
executors:
  app:
    docker:
      - image: python:3.7.4-stretch
    enviroment:
      PYTHONPATH: /app/savoten/
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: ~/working_dir
