version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Create .env
          command: cat << EOF >> .env\UID=$(id -u)\GID=$(id -g)\EOF
          command: cat .env
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: Run tests
          command: docker-compose exec app pipenv run scripts/run_tests
